[package]
name = "gcode-simulator"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]

[dependencies]
gcode = { path = "../gcode" }
libm = "0.1"
sum_type = "0.1.1"

[dev-dependencies]
pretty_assertions = "0.5"
approx = "0.3"
