os: Visual Studio 2015

environment:
  matrix:
    - channel: 1.31.0
    # first release with editions on stable
      target: x86_64-pc-windows-msvc
    - channel: 1.31.0
      target: x86_64-pc-windows-msvc
      cargoflags: --all-features

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo test --verbose %cargoflags%
