language: rust
rust:
  - 1.27.0
  - stable
  - nightly

cache:
  - cargo

install:
  - source ~/.cargo/env || true
  - command -v cbindgen >/dev/null 2>&1 || cargo install --debug cbindgen

script:
  - cargo build --verbose --target $TARGET
  - cargo test --verbose --target $TARGET
  - cargo build --release --verbose --target $TARGET
  - cargo test --release --verbose --target $TARGET

before_cache:
  - chmod -R a+r $HOME/.cargo

before_deploy:
  - cargo doc --all --verbose
  - cbindgen --output gcode.h
  - cp target/$TARGET/release/libgcode.{a,so} .
  - export VERSION=$(cat Cargo.toml | awk '$1 == "version" { print $3 }' | tr -d '"')
  - zip gcode.v$VERSION.$TARGET.zip gcode.h libgcode.so libgcode.a

env:
  global:
  - TARGET=x86_64-unknown-linux-gnu
  - secure: KYlhj8S0cH4AT1fkrecOIMmJrvnC3nUDQZ+fTtstVvm+rrV6KqwRqy6WfekRNq3Le6S7SsH5SyyJFfdFFkHVtpUSnYvd2pxy7mrYpgFba/9vJxndJYSqI6TuxJ5tx+HxouCEFVNZg8f1De+RtGayD2f4xOixRbSHQO3kzH2Cz0pzTBMas5cfveImjHwc+abwp/tp0VKgCz/91V698/cDC0RWVX6aUSe3z1lBN/mmnqXLiDLqcT1xlQqq5JJZ2SjCnLoSnwqMPZzWGBIxz9mvqsE9531pgj1YWYUkQGGNLotwdrpkRhTALVTZJBoKcDqN9rAvdIrw32ufJ2RwO6AjBonurCcZwCYzGDxSulyjrXchKN+hPQ/qpz5kwAh8o9vLfExVYP/gKaDTKVAiva8Zdi3tT/8WYhXm2P+UH2U4qFuhgYxr/bi/HIsVqPRgurKtgK0keCHh+h6VqGOpy49Td9r3uCzWdCiC2vawThQEPNl3NF0BhA5mpQkEEtAcO7tKagvptBaZTLP1gxtT1eTcYvWypff4Eo3m1TXFf4dkKk23gblK9UAzdbqrH0WqFWLLyHv+vwCNA6hdV4BfiiS/dseuB/66tQ6so3vwoVcTyPEy9U1cFzCxu64J1OcmTY1h72fToAiBNjoDevzofbZPduQruVYLqZj74e1tvl4xPOM=

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: target/doc
    on:
      branch: master

