language: rust

env:
  global:
    - secure: KYlhj8S0cH4AT1fkrecOIMmJrvnC3nUDQZ+fTtstVvm+rrV6KqwRqy6WfekRNq3Le6S7SsH5SyyJFfdFFkHVtpUSnYvd2pxy7mrYpgFba/9vJxndJYSqI6TuxJ5tx+HxouCEFVNZg8f1De+RtGayD2f4xOixRbSHQO3kzH2Cz0pzTBMas5cfveImjHwc+abwp/tp0VKgCz/91V698/cDC0RWVX6aUSe3z1lBN/mmnqXLiDLqcT1xlQqq5JJZ2SjCnLoSnwqMPZzWGBIxz9mvqsE9531pgj1YWYUkQGGNLotwdrpkRhTALVTZJBoKcDqN9rAvdIrw32ufJ2RwO6AjBonurCcZwCYzGDxSulyjrXchKN+hPQ/qpz5kwAh8o9vLfExVYP/gKaDTKVAiva8Zdi3tT/8WYhXm2P+UH2U4qFuhgYxr/bi/HIsVqPRgurKtgK0keCHh+h6VqGOpy49Td9r3uCzWdCiC2vawThQEPNl3NF0BhA5mpQkEEtAcO7tKagvptBaZTLP1gxtT1eTcYvWypff4Eo3m1TXFf4dkKk23gblK9UAzdbqrH0WqFWLLyHv+vwCNA6hdV4BfiiS/dseuB/66tQ6so3vwoVcTyPEy9U1cFzCxu64J1OcmTY1h72fToAiBNjoDevzofbZPduQruVYLqZj74e1tvl4xPOM=

matrix:
  include:
    # MSRV from arrayvec
    - rust: 1.36.0
    # and check each feature individually
    - env: FEATURES="--no-default-features --features serde-1"
    - env: FEATURES="--no-default-features --features std"
    # Make sure it compiles without std by targeting an embedded platform
    - env: 
      - TARGET=thumbv7em-none-eabihf
      - FEATURES=--no-default-features
      script:
      - cd gcode
      - cargo build --verbose $FEATURES $TARGET

    # Use nightly for better docs
    - env: 
      - FEATURES=--all-features 
      - RUSTDOCFLAGS="--cfg docsrs"
      rust: nightly

before_script:
  - |
    if [ ! -z "$TARGET" ]; then
      rustup target add $TARGET
      export TARGET="--target $TARGET"
    fi
  - set -e

script:
  - cd gcode
  - cargo build --no-default-features
  - cargo build --verbose $FEATURES $TARGET
  - cargo test --verbose $FEATURES $TARGET
  - cargo doc --verbose $FEATURES $TARGET

after_script: set +e

before_cache:
  - chmod -R a+r $HOME/.cargo

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    local-dir: target/doc
    on:
      branch: master
      rust: nightly

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never

