[package]
authors = ["Michael-F-Bryan <michaelfbryan@gmail.com>"]
name = "gcode"
version = "0.3.0"
description = "A gcode parser for no-std applications."
license = "MIT"

[dev-dependencies]
quickcheck = "0.6.2"
rand = "0.4.2"

[dependencies]
arrayvec = "0.4.7"
