[package]
name = "gcode"
version = "0.1.0"
authors = ["Michael-F-Bryan <michaelfbryan@gmail.com>"]

[dependencies]
log = {version = "^0.3", default_features = false}
arrayvec = {version="^0.3", default_features = false}

[dev-dependencies]
env_logger = "*"
