[package]
authors = ["Michael-F-Bryan <michaelfbryan@gmail.com>"]
name = "gcode"
version = "0.3.0"
description = "A gcode parser for no-std applications."
license = "MIT"

[dependencies]
nom = { version = "4.0.0-beta2", default_features = false, features = [] }

[dev-dependencies]
quickcheck = "0.6.2"
