[package]
authors = ["Michael-F-Bryan <michaelfbryan@gmail.com>"]
name = "gcode"
version = "0.3.0"
description = "A gcode parser for no-std applications."
license = "MIT"

[dev-dependencies]
pretty_assertions = "0.5.1"

[dependencies]
arrayvec = "0.4.7"
cfg-if = { version = "0.1.4", optional = true }

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[features]
default = ["ffi"]
ffi = ["cfg-if"]
