[package]
authors = ["Michael-F-Bryan <michaelfbryan@gmail.com>"]
name = "gcode"
version = "0.2.0"

[dependencies]

[dependencies.arrayvec]
default_features = false
version = "^0.3"

[dev-dependencies]
quickcheck = "0.4.1"
rand = "0.3.15"

[features]
default = []
nightly = []
