[package]
name = "gcode"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]

[dependencies]
arrayvec = { version = "0.4", default-features = false }
libm = "0.1"
cfg-if = "0.1"

[features]
default = []
std = []
