on: [push, pull_request]

name: Continuous integration


jobs:
  check:
    name: Compile and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
          - stable
          # MSRV - Relatively recent compiler version
          - 1.46.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --verbose --manifest-path gcode/Cargo.toml
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --manifest-path gcode/Cargo.toml
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --manifest-path gcode/Cargo.toml

  api-docs:
    name: Publish API Docs to GitHub Pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --verbose --manifest-path gcode/Cargo.toml
      - name: Redirect top-level GitHub Pages
        run: "echo '<meta http-equiv=\"refresh\" content=\"0; url=gcode/index.html\" />' > target/doc/index.html"
        shell: bash
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: target/doc
        env:
          GITHUB_PAT: ${{ secrets.GH_PAGES_ACCESS_TOKEN  }}

